export const bookingData = {
    "majorColumns": ["Name", "Address", "Phone", "Homepage"],
    "allMajorRows": [
        ["일죽 썬밸리CC", "충북 음성군 삼성면 대사리 500-16", "043-881-5307", "http://www.sunvalleycc.co.kr"],
    ],
    "minorColumns": ["BookingInfo"],
    "allMinorRows": [
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["All that glitters is not gold.", "N"],
        ["Eighty percent of success is showing up.", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["Eighty percent of success is showing up.", "Y"],
        ["Elementary, my dear Watson.", "N"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["Elementary, my dear Watson.", "N"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["Eighty percent of success is showing up.", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["All the world’s a stage, and all the men and women merely players.", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["All that glitters is not gold.", "N"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["Elementary, my dear Watson.", "N"],
        ["All the world’s a stage, and all the men and women merely players.", "Y"],
        ["All the world’s a stage, and all the men and women merely players.", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["Elementary, my dear Watson.", "N"],
        ["All the world’s a stage, and all the men and women merely players.", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["All the world’s a stage, and all the men and women merely players.", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["All that glitters is not gold.", "N"],
        ["All that glitters is not gold.", "N"],
        ["Eighty percent of success is showing up.", "Y"],
        ["Eighty percent of success is showing up.", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["All that glitters is not gold.", "N"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["Elementary, my dear Watson.", "N"],
        ["Elementary, my dear Watson.", "N"],
        ["Eighty percent of success is showing up.", "Y"],
        ["Eighty percent of success is showing up.", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["All that glitters is not gold.", "N"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["Elementary, my dear Watson.", "N"],
        ["All that glitters is not gold.", "N"],
        ["All that glitters is not gold.", "N"],
        ["Magic Mirror on the wall, who is the fairest one of all?", "Y"],
        ["A rose by any other name would smell as sweet.", "Y"],
        ["All that glitters is not gold.", "N"]
    ]
};